apiVersion: batch/v1
kind: Job
metadata:
  name: sqlite-restore
  namespace: pra
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: alpine
          command: ["/bin/sh","-c"]
          args:
            - |
              # On choisit manuellement le point de restauration
              cp /backup/backup-2026-04-24-14-00.db /data/app.db
              echo "Restauration manuelle réussie"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: backup
              mountPath: /backup
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pra-data
        - name: backup
          persistentVolumeClaim:
            claimName: pra-backup
